### ISSUE TITLE
Got this error today

### ISSUE THREAD

**Issue by bridgestew** [Lynx3d/tinker_tools#1] opened 2016-05-28 20:33 UTC
Error: TinkerTools/Modules/Flying.lua:26: attempt to index local 'data' (a nil value)
    In TinkerTools / TinkerTools.DFlyingPlaceBtn:Event.UI.Input.Mouse.Left.Click
stack traceback:
    [C]: in function '__index'
    TinkerTools/Modules/Flying.lua:26: in function <TinkerTools/Modules/Flying.lua:21>

I tried to use Tribal magic in Auditorium Carnos Plaza dim that contains 691 of 1200 items. Hope that information helps! 

P.S. This addon is amazing!

**Comment by Lynx3d** [comment] 2016-06-03 02:08
While I can't directly reproduce the error, I think I see where it comes from.
Basically, under certain circumstances Rift reports an item ID for a slot although the slot is empty, e.g. when using up the last item of a stack when crafting. This causes Inspect.Item.Detail() return nil on that slot, since it is in fact empty.

Should be fixed now.

**Closed as completed by Lynx3d** 2016-06-03 02:08 UTC
